# Generated by Django 5.0.7 on 2024-09-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentaweb', '0002_conversationhistory_delete_conversa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationhistory',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
