# Generated by Django 5.0.7 on 2024-09-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentaweb', '0003_alter_conversationhistory_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConversationHistory',
            new_name='Historico_Conversa',
        ),
    ]
