# Generated by Django 5.0.7 on 2024-09-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentaweb', '0004_rename_conversationhistory_historico_conversa'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico_conversa',
            name='response',
            field=models.TextField(default='Resposta Padrão'),
            preserve_default=False,
        ),
    ]
