# Generated by Django 5.0.7 on 2024-09-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentaweb', '0005_historico_conversa_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico_conversa',
            name='nivel_complexidade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
