# Generated by Django 5.1.1 on 2024-11-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentaweb', '0006_historico_conversa_nivel_complexidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico_Conversa_Transferida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('nivel_complexidade', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
